config/routes.rb
Mahatma::Application.routes.draw do

  root :to => "ips#index"

  match "/login" => "auth#login"
  match "/logout" => "auth#logout"

  match "stats/department/:department_id(/:from_date/:to_date)" => "stats#show_department"
  match "stats/(:from_date/:to_date)" => "stats#show", :as => "stats"

  get "reports/department_ips"

  resources :users

  resources :departments

  resources :ips

  resources :persons

  resources :buildings

end

app/models/department.rb
class Department < ActiveRecord::Base
  validates_presence_of :name, :person_id
  validates_uniqueness_of :name
  validates_associated :person
  acts_as_nested_set
  belongs_to :person
  has_many :ips
  has_many :inbounds, :through => :ips
  has_many :outbounds, :through => :ips

  def total_traffic(dir,type,from_date,to_date)
    res = 0
    all_ips.each do |ip|
      res += ip.traffic(dir,type,from_date,to_date)
    end
    res
  end

  def all_ips
    res = []
    self_and_descendants.each {|d| res += d.ips}
    res
  end

end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  # GET /departments
  # GET /departments.json
  def index
    @departments = Department.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @departments }
    end
  end

  # GET /departments/1
  # GET /departments/1.json
  def show
    @department = Department.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @department }
    end
  end

  # GET /departments/new
  # GET /departments/new.json
  def new
    @department = Department.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @department }
    end
  end

  # GET /departments/1/edit
  def edit
    @department = Department.find(params[:id])
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(params[:department])

    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, notice: 'Department was successfully created.' }
        format.json { render json: @department, status: :created, location: @department }
      else
        format.html { render action: "new" }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /departments/1
  # PUT /departments/1.json
  def update
    @department = Department.find(params[:id])

    respond_to do |format|
      if @department.update_attributes(params[:department])
        format.html { redirect_to @department, notice: 'Department was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department = Department.find(params[:id])
    @department.destroy

    respond_to do |format|
      format.html { redirect_to departments_url }
      format.json { head :ok }
    end
  end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_form.html.erb
<%= form_for(@department) do |f| %>
  <% if @department.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
      <% @department.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :person_id %><br />
    <%= f.collection_select(:person_id,Person.all,:id,:name) %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br />
    <%= f.collection_select(:parent_id,Department.all,:id,:name,:include_blank => true) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/departments/edit.html.erb
<h1>Editing department</h1>

<%= render 'form' %>

<%= link_to 'Show', @department %> |
<%= link_to 'Back', departments_path %>

app/views/departments/index.html.erb
<h1>Listing departments</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Person</th>
    <th>Parent</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @departments.each do |department| %>
  <tr>
    <td><%= department.name %></td>
    <td><%= department.person.name if department.person %></td>
    <td><%= department.parent.name if department.parent %></td>
    <td><%= link_to 'Show', department %></td>
    <td><%= link_to 'Edit', edit_department_path(department) %></td>
    <td><%= link_to 'Destroy', department, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Department', new_department_path %>

app/views/departments/new.html.erb
<h1>New department</h1>

<%= render 'form' %>

<%= link_to 'Back', departments_path %>

app/views/departments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @department.name %>
</p>

<p>
  <b>Person:</b>
  <%= @department.person.name if @department.person %>
</p>

<p>
  <b>Parent:</b>
  <%= @department.parent.name if @department.parent %>
</p>


<%= link_to 'Edit', edit_department_path(@department) %> |
<%= link_to 'Back', departments_path %>