config/routes.rb
Mahatma::Application.routes.draw do

  root :to => "ips#index"

  match "/login" => "auth#login"
  match "/logout" => "auth#logout"

  match "stats/department/:department_id(/:from_date/:to_date)" => "stats#show_department"
  match "stats/(:from_date/:to_date)" => "stats#show", :as => "stats"

  get "reports/department_ips"

  resources :users

  resources :departments

  resources :ips

  resources :persons

  resources :buildings

end

app/models/person.rb
class Person < ActiveRecord::Base
  set_table_name :persons
  validates_presence_of :name
  validates_uniqueness_of :name
  has_many :departments
  has_many :ips
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  # GET /persons
  # GET /persons.json
  def index
    @persons = Person.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @persons }
    end
  end

  # GET /persons/1
  # GET /persons/1.json
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  # GET /persons/new
  # GET /persons/new.json
  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
  end

  # GET /persons/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /persons
  # POST /persons.json
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render json: @person, status: :created, location: @person }
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /persons/1
  # PUT /persons/1.json
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /persons/1
  # DELETE /persons/1.json
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to persons_url }
      format.json { head :ok }
    end
  end
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/views/persons/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/persons/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', persons_path %>

app/views/persons/index.html.erb
<h1>Listing persons</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Phone</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @persons.each do |person| %>
  <tr>
    <td><%= person.name %></td>
    <td><%= person.email %></td>
    <td><%= person.phone %></td>
    <td><%= link_to 'Show', person %></td>
    <td><%= link_to 'Edit', edit_person_path(person) %></td>
    <td><%= link_to 'Destroy', person, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Person', new_person_path %>

app/views/persons/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', persons_path %>

app/views/persons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @person.name %>
</p>

<p>
  <b>Email:</b>
  <%= @person.email %>
</p>

<p>
  <b>Phone:</b>
  <%= @person.phone %>
</p>


<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', persons_path %>